email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Padraic Renaghan"
tagline: ""
description: "Follow <a href=\"https://micro.blog/padraic\">@padraic on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/padraic\">@padraic on Micro.blog</a>."
baseurl: ""
url: "http://blog.renaghan.com"
markdown: "kramdown"
username: "padraic"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Padraic Renaghan"
name: "Padraic Renaghan"
gravatar_hash: "c0e0388b839b98157c4fd1f80a5bc7cd"
avatar: "https://www.gravatar.com/avatar/c0e0388b839b98157c4fd1f80a5bc7cd?s=160"
full_name: "Padraic Renaghan"
bio: ""
twitter_username: "prenagha"
github_username: "prenagha"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"