# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# - title: Your awesome title
email: your-email@domain.com

# - avatar: han-solo.jpg
full_# - name: Han Solo
# - bio: Swindler. Scoundrel. Bad Ass.

# Build settings
# - markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Output
# - permalink: /:year/:month/:slug/

title: "Padraic Renaghan"
tagline: ""
description: "Follow <a href=\"https://micro.blog/padraic\">@padraic on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/padraic\">@padraic on Micro.blog</a>."
baseurl: ""
url: "http://blog.renaghan.com"
markdown: "kramdown"
username: "padraic"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Padraic Renaghan"
name: "Padraic Renaghan"
gravatar_hash: "c0e0388b839b98157c4fd1f80a5bc7cd"
avatar: "https://www.gravatar.com/avatar/c0e0388b839b98157c4fd1f80a5bc7cd?s=160"
full_name: "Padraic Renaghan"
bio: ""
twitter_username: "prenagha"
github_username: "prenagha"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"